// lib/utils/constants.ts
export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const reasonOptions: Record<string, Record<string, string[]>> = {
    CANCELLED: {
        "CIERRE DEFINITIVO": [
            "TEMAS ECONOMICOS/BAJAS VENTAS - NEGOCIO DEJO DE SER RENTABLE",
            "TEMAS ECONOMICOS/BAJAS VENTAS - FALTA DE CAPITAL PARA INVERTIR",
            "TEMAS ECONOMICOS/INCREMENTO-NO RENOVACIÓN DEL ALQUILER", 
            "COLABORADOR/FAMILIAR DELICADO DE SALUD",
            "FALLECIMIENTO DEL COLABORADOR/FAMILIAR",
            "INSEGURIDAD CIUDADANA (ROBOS FRECUENTES, EXTORSIÓN)",
            "PROBLEMAS CON LA LICENCIA MUNICIPALIDAD/MINSA",
            "COLABORADOR CON FALTA DE TIEMPO PORQUE SE DEDICA A OTRA ACTIVIDAD ECONOMICA"
        ],
        "MALA COLABORACIÓN": [
            "NO GUARDA LAS COMPRAS/IMPIDE CONTEO EN ALGUNAS ZONAS DE LA TIENDA",
            "POR FALTA DE TIEMPO DEL COLABORADOR",
            "INCONFORMIDAD CON INCENTIVO",
            "MALA RELACIÓN CON AUDITOR",
            "REPROGRAMACIÓN CONSTANTE",
            "CONTADOR SE LLEVA LOS DOCUMENTOS DE COMPRA"
        ],
        "CAMBIO DE RUBRO": [
            "CAMBIÓ A BODEGA GENERALISTA",
            "CAMBIÓ A KIOSCO",
            "CAMBIÓ A ON PREMISE",
            "CAMBIÓ A BODEGA DE ASEO",
            "CAMBIÓ A LICORERÍA",
            "CAMBIÓ A OTRO TIPO DE TIENDA NO ESPECIFICADA ANTERIORMENTE"
        ],
        "MALA CONTRATACIÓN": [
            "GESTIÓN DE CONTRATACIÓN SE REALIZO DE MANERA INCOMPLETA",
            "NO GUARDA LAS COMPRAS/IMPIDE CONTEO EN ALGUNAS ZONAS DE LA TIENDA"
        ],
        "CAMBIO DE DUEÑO/ADMINISTRADOR SIN ÉXITO EN RECONTRATO": [],
        "DEJÓ DE MANEJAR EL ÍNDICE": [
            "BAJAS VENTAS",
            "ESPACIO REDUCIDO",
            "PERMISOS MUNICIPALES",
            "OTRAS RAZONES"
        ],
        "NEGOCIO COMPARTE MERCADERÍA": [],
        "COLABORADOR(A) EN VIAJE PROLONGADO": [],
        "COLABORADOR(A) SIN UBICAR": [],
        "ZONA PELIGROSA": [],
        "CIERRE POR REMODELACIÓN INTERNA/EXTERNA PROLONGADO": [],
        "ANULACIÓN POR SOBREMUESTRA": [],
    },
    NOTAUDITED: {
        "COLABORADOR(A) SIN UBICAR": [],
        "COLABORADOR(A) DE VIAJE": [],
        "COLABORADOR(A) DE VACACIONES": [],
        "PROBLEMAS FAMILIARES O DE SALUD": [],
        "CIERRE POR REMODELACIÓN INTERNA/EXTERNA": [],
        "SIN PRODUCTOS AUDITABLES ESTE PERIODO": [],
        "CAMBIO DE DUEÑO/ADMINISTRADOR": [],
        "COLABORADOR CERRO TEMPORALMENTE PORQUE SE DEDICA A OTRA ACTIVIDAD ECONOMICA": [],
        "MALA COLABORACIÓN": [
            "NO GUARDA LAS COMPRAS/IMPIDE CONTEO EN ALGUNAS ZONAS DE LA TIENDA",
            "POR FALTA DE TIEMPO DEL COLABORADOR"
        ],
        "NEGOCIO SE ENCONTRÓ CERRADO - ABRE SIGUIENTE MES": [],
        "SIN DOCUMENTOS DE COMPRA": [],
        "TIENDA EXCEDIÓ LOS 40 DT": [],
        "TIENDA CERRADA POR PARO/HUELGA": [],
        "TIENDA CERRADA POR FENÓMENOS NATURALES": [],
        "OTRAS RAZONES": [],
    },
    "FUERA DE DT": {
        "COLABORADOR(A) DE VIAJE": [],
        "COLABORADOR REPROGRAMÓ CITA DE ATENCIÓN": [],
        "PROBLEMAS FAMILIARES O DE SALUD": [],
        "DESCUIDO DE AUDITOR": [],
        "LICENCIA MEDICA DE AUDITOR": [],
        "ROBO DEL EQUIPO DE AUDITOR": [],
        "MEJORA DE TFA / ZONIFICACIÓN": [],
        "CIERRE POR REMODELACIÓN INTERNA/EXTERNA": [],
        "COLABORADOR(A) SIN UBICAR": [],
        "TIENDA CERRADA TEMPORALMENTE POR PARO/HUELGAS": [],
        "TIENDA CERRADA TEMPORALMENTE POR FENOMENOS NATURALES": [],
        "OTRAS RAZONES": [],
    }
};